/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2.pdc.gui;

import java.util.Arrays;
import java.util.List;
import javax.swing.JButton;
import project2.pdc.model.Battle;
import project2.pdc.model.Card;
import project2.pdc.model.Player;
import project2.pdc.model.Round;

/**
 *
 * @author abdulh
 */
public class BattleGUI extends javax.swing.JFrame {

    private final Battle battle;
    private final List<javax.swing.JButton> cardButtons;
    
    /**
     * Creates new form CardJitsuGUI
     * @param battle
     */
    public BattleGUI(final Battle battle) {
        this.battle = battle;
        this.initComponents();
        
        this.cardButtons = Arrays.asList(this.card1Button, this.card2Button, this.card3Button, this.card4Button, this.card5Button);
        this.updateHand();
        
        this.nextRoundButton.setEnabled(false);
        
        System.out.println(this.battle.getPlayer());
        System.out.println(this.battle.getRobot());
    }
    
    private void updateHand() {
        List<Card> playerHand = this.battle.getPlayer().getHand();
        for (int i = 0; i < Player.HAND_SIZE; i++) {
            Card card = playerHand.get(i);
            JButton cardButton = this.cardButtons.get(i);
            cardButton.setText("<html><center><h1>" + card.getLevel() + "</h1>" + card.getColour().name() + " " + card.getElement() + "</center></html>");
            cardButton.setBackground(card.getColour().value);
        }
    }
    
    private void playRound(int index) {
        this.battle.playRound(index);
        this.battle.drawCards();
        Round round = this.battle.getLatestRound();
        System.out.println("\nROUND: " + this.battle.getRoundNumber());
        System.out.println(round.getPlayer1().getName() + " used " + round.getPlayer1Card());
        System.out.println(round.getPlayer2().getName() + " used " + round.getPlayer2Card());
        System.out.println(round.getRoundWinningPlayer().get().getName() + " won with " + round.getRoundWinningCard().get());
        System.out.println(this.battle.getPlayer());
        System.out.println(this.battle.getRobot());
        this.updateHand();
        
        this.nextRoundButton.setEnabled(true);
        for (JButton cardButton : this.cardButtons) {
            cardButton.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        card1Button = new javax.swing.JButton();
        card2Button = new javax.swing.JButton();
        card3Button = new javax.swing.JButton();
        card4Button = new javax.swing.JButton();
        card5Button = new javax.swing.JButton();
        nextRoundButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 500));
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        card1Button.setPreferredSize(new java.awt.Dimension(100, 150));
        card1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card1ButtonActionPerformed(evt);
            }
        });

        card2Button.setLabel("");
        card2Button.setPreferredSize(new java.awt.Dimension(100, 150));
        card2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card2ButtonActionPerformed(evt);
            }
        });

        card3Button.setPreferredSize(new java.awt.Dimension(100, 150));
        card3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card3ButtonActionPerformed(evt);
            }
        });

        card4Button.setPreferredSize(new java.awt.Dimension(100, 150));
        card4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card4ButtonActionPerformed(evt);
            }
        });

        card5Button.setPreferredSize(new java.awt.Dimension(100, 150));
        card5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card5ButtonActionPerformed(evt);
            }
        });

        nextRoundButton.setText("Next Round");
        nextRoundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRoundButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(card1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(card2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(card3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(card4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(card5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(nextRoundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(nextRoundButton)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card1Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card2Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card3Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card4Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card5Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        card1Button.getAccessibleContext().setAccessibleName("");
        card2Button.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void card1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card1ButtonActionPerformed
        playRound(0);
    }//GEN-LAST:event_card1ButtonActionPerformed

    private void card2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card2ButtonActionPerformed
        playRound(1);
    }//GEN-LAST:event_card2ButtonActionPerformed

    private void card3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card3ButtonActionPerformed
        playRound(2);
    }//GEN-LAST:event_card3ButtonActionPerformed

    private void card4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card4ButtonActionPerformed
        playRound(3);
    }//GEN-LAST:event_card4ButtonActionPerformed

    private void card5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card5ButtonActionPerformed
        playRound(4);
    }//GEN-LAST:event_card5ButtonActionPerformed

    private void nextRoundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRoundButtonActionPerformed
        this.nextRoundButton.setEnabled(false);
        for (JButton cardButton : this.cardButtons) {
            cardButton.setEnabled(true);
        }
    }//GEN-LAST:event_nextRoundButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton card1Button;
    private javax.swing.JButton card2Button;
    private javax.swing.JButton card3Button;
    private javax.swing.JButton card4Button;
    private javax.swing.JButton card5Button;
    private javax.swing.JButton nextRoundButton;
    // End of variables declaration//GEN-END:variables
}
