/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.reference;

/**
 *
 * @author User
 */
public class BattleGUI extends javax.swing.JFrame {

    /**
     * Creates new form BattleGUI
     */
    public BattleGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batlePanel = new javax.swing.JPanel();
        roundMessageLabel = new javax.swing.JLabel();
        roundNumberLabel = new javax.swing.JLabel();
        playerWinningCardsPanel = new javax.swing.JPanel();
        playerIceWinningCardsLabel = new javax.swing.JLabel();
        playerFireWinningCardsLabel = new javax.swing.JLabel();
        playerWaterWinningCardsLabel = new javax.swing.JLabel();
        robotWinningCardsPanel = new javax.swing.JPanel();
        robotIceWinningCardsLabel = new javax.swing.JLabel();
        robotFireWinningCardsLabel = new javax.swing.JLabel();
        robotWaterWinningCardsLabel = new javax.swing.JLabel();
        handPanel = new javax.swing.JPanel();
        cardButton1 = new javax.swing.JButton();
        cardButton2 = new javax.swing.JButton();
        cardButton3 = new javax.swing.JButton();
        cardButton4 = new javax.swing.JButton();
        cardButton5 = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Card Jitsu");
        setMinimumSize(new java.awt.Dimension(550, 550));
        setResizable(false);

        roundMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roundMessageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundMessageLabel.setText("Player's magenta water [12] beat Robot's magenta water [12]");

        roundNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roundNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roundNumberLabel.setText("ROUND 10");

        playerWinningCardsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Player's Winning Cards"));

        playerIceWinningCardsLabel.setText("ICE: ");

        playerFireWinningCardsLabel.setText("FIRE: ");

        playerWaterWinningCardsLabel.setText("WATER:");

        javax.swing.GroupLayout playerWinningCardsPanelLayout = new javax.swing.GroupLayout(playerWinningCardsPanel);
        playerWinningCardsPanel.setLayout(playerWinningCardsPanelLayout);
        playerWinningCardsPanelLayout.setHorizontalGroup(
            playerWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerWinningCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerIceWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerFireWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerWaterWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        playerWinningCardsPanelLayout.setVerticalGroup(
            playerWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerWinningCardsPanelLayout.createSequentialGroup()
                .addComponent(playerIceWinningCardsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerFireWinningCardsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerWaterWinningCardsLabel))
        );

        robotWinningCardsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Robot's Winning Cards"));

        robotIceWinningCardsLabel.setText("ICE: ");

        robotFireWinningCardsLabel.setText("FIRE: ");

        robotWaterWinningCardsLabel.setText("WATER:");

        javax.swing.GroupLayout robotWinningCardsPanelLayout = new javax.swing.GroupLayout(robotWinningCardsPanel);
        robotWinningCardsPanel.setLayout(robotWinningCardsPanelLayout);
        robotWinningCardsPanelLayout.setHorizontalGroup(
            robotWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotWinningCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(robotWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(robotIceWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(robotFireWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(robotWaterWinningCardsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        robotWinningCardsPanelLayout.setVerticalGroup(
            robotWinningCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(robotWinningCardsPanelLayout.createSequentialGroup()
                .addComponent(robotIceWinningCardsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(robotFireWinningCardsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(robotWaterWinningCardsLabel))
        );

        handPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hand of Cards"));

        cardButton1.setText("<html>\n<h4>12</h4>\nMagenta\n<br/>\nWater\n</html>");
        cardButton1.setActionCommand("Card 1");
        cardButton1.setMaximumSize(new java.awt.Dimension(75, 125));
        cardButton1.setMinimumSize(new java.awt.Dimension(75, 125));
        cardButton1.setPreferredSize(new java.awt.Dimension(75, 125));

        cardButton2.setText("<html>\n<h4>12</h4>\nMagenta\n<br/>\nWater\n</html>");
        cardButton2.setActionCommand("Card 2");
        cardButton2.setMaximumSize(new java.awt.Dimension(75, 125));
        cardButton2.setMinimumSize(new java.awt.Dimension(75, 125));
        cardButton2.setPreferredSize(new java.awt.Dimension(75, 125));

        cardButton3.setText("<html>\n<h4>12</h4>\nMagenta\n<br/>\nWater\n</html>");
        cardButton3.setActionCommand("Card 3");
        cardButton3.setMaximumSize(new java.awt.Dimension(75, 125));
        cardButton3.setMinimumSize(new java.awt.Dimension(75, 125));
        cardButton3.setPreferredSize(new java.awt.Dimension(75, 125));

        cardButton4.setText("<html>\n<h4>12</h4>\nMagenta\n<br/>\nWater\n</html>");
        cardButton4.setActionCommand("Card 4");
        cardButton4.setMaximumSize(new java.awt.Dimension(75, 125));
        cardButton4.setMinimumSize(new java.awt.Dimension(75, 125));
        cardButton4.setPreferredSize(new java.awt.Dimension(75, 125));

        cardButton5.setText("<html>\n<h4>12</h4>\nMagenta\n<br/>\nWater\n</html>");
        cardButton5.setActionCommand("Card 5");
        cardButton5.setMaximumSize(new java.awt.Dimension(75, 125));
        cardButton5.setMinimumSize(new java.awt.Dimension(75, 125));
        cardButton5.setPreferredSize(new java.awt.Dimension(75, 125));

        javax.swing.GroupLayout handPanelLayout = new javax.swing.GroupLayout(handPanel);
        handPanel.setLayout(handPanelLayout);
        handPanelLayout.setHorizontalGroup(
            handPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cardButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(cardButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(cardButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        handPanelLayout.setVerticalGroup(
            handPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handPanelLayout.createSequentialGroup()
                .addGroup(handPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        helpButton.setText("Help");

        quitButton.setText("Quit");

        javax.swing.GroupLayout batlePanelLayout = new javax.swing.GroupLayout(batlePanel);
        batlePanel.setLayout(batlePanelLayout);
        batlePanelLayout.setHorizontalGroup(
            batlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(batlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(playerWinningCardsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(robotWinningCardsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(handPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(batlePanelLayout.createSequentialGroup()
                        .addComponent(helpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitButton)))
                .addContainerGap())
        );
        batlePanelLayout.setVerticalGroup(
            batlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundNumberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerWinningCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(robotWinningCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(handPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(batlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpButton)
                    .addComponent(quitButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(batlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BattleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BattleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel batlePanel;
    private javax.swing.JButton cardButton1;
    private javax.swing.JButton cardButton2;
    private javax.swing.JButton cardButton3;
    private javax.swing.JButton cardButton4;
    private javax.swing.JButton cardButton5;
    private javax.swing.JPanel handPanel;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel playerFireWinningCardsLabel;
    private javax.swing.JLabel playerIceWinningCardsLabel;
    private javax.swing.JLabel playerWaterWinningCardsLabel;
    private javax.swing.JPanel playerWinningCardsPanel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel robotFireWinningCardsLabel;
    private javax.swing.JLabel robotIceWinningCardsLabel;
    private javax.swing.JLabel robotWaterWinningCardsLabel;
    private javax.swing.JPanel robotWinningCardsPanel;
    private javax.swing.JLabel roundMessageLabel;
    private javax.swing.JLabel roundNumberLabel;
    // End of variables declaration//GEN-END:variables
}
